dist: xenial
language: node_js
addons:
  apt:
    packages:
    - libgconf-2-4
services:
- docker
cache:
  npm: true
  directories:
  - "~/.cache"
install:
- npm ci
script:
- npm run lint
- npm run test
- npm run e2e
- npm run e2e:docker
deploy:
- provider: heroku
  app: impasse
  api_key:
    secure: YNRW0Vct6Htm8XlA2F7etxb+DB1pjJML/R+7P6Z5lrpDi04k0XQOITh6dksREsa9syt0iU0Zyd5uKPPU0xN8smTINw3ukcJA07rzRKaEb0hszHezDWkZ7HkmpvR/xP3k977hAv0Myxy/UL7kGpwUCQwIl2fFYhdwK+zFLe0ZDOZ6BJLFUXsvDBxaPeKjwdfCQ1OaYxwXYgjOFssRbOASyuklq3ZVop26DU1bO/rpqYxn2q99PJuD4Q9CyinUOqwDVF6Cf2krfbBSuOviDV/rduGU9II40ZjFWqtlfX3A8A92laR4aLvybfa/CHxtd7eR4I9pVMkX1r94pVkC5OxvmpGXqoeptYlo0g/cCCtIrsavEAxx7UTQSBPEByjpDWHQFkqca3A7Vgqi1Xa76SEQehh5CihbWDkJjrQmsxXZbbQc63XEvBMmU4wBIcQCUM1lp/5FAKAHjVFwtNCG5DIjckT7734AZjBIl2O+yysEzeIB2oabFUOG0Uoh55CpZVthPy/Zf1ME9KZ0lrWr5x0IcOwDrnpa6XDS62qnEBgDoj8ytu1GeJA46S+kmUrrXLK51jCYbWe3mGUvGA+c01NWWCvpQWNpR5SkUc8nSpDQvD5D4MhPQb2LeWV1jQGeACB0cjGopKOXfCtdPZdHry0dgrb3AulFt8EkECOt4NfX8og=
  on:
    tags: true
- provider: script
  script: ./bin/deploy-docker.sh
  on:
    tags: true
