version: 2.1

defaults: &defaults
  docker:
    - image: circleci/node:dubnium

docker-e2e: &docker-e2e
  steps:
    - checkout
    - setup_remote_docker
    - run:
        name: Docker E2E
        command: docker-compose run e2e run e2e:run

jobs:
  deps:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - starter-kit-deps-{{ checksum "package-lock.json" }}
            - starter-kit-deps- # fallback
      - run:
          name: Install dependencies
          command: npm ci
      - save_cache:
          key: starter-kit-deps-{{ checksum "package-lock.json" }}
          paths:
            - "~/.cache"
            - "~/.npm"
  test:
    <<: *defaults
    environment:
      CYPRESS_INSTALL_BINARY: 0
    steps:
      - checkout
      - restore_cache:
          keys:
            - starter-kit-deps-{{ checksum "package-lock.json" }}
            - starter-kit-deps- # fallback
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: Lint source code
          command: npm run lint
      - run:
          name: Test source code
          command: npm run test
      - store_test_results:
          path: ./reports
  e2e:
    docker:
      - image: cypress/base:10
    steps:
      - checkout
      - restore_cache:
          keys:
            - starter-kit-deps-{{ checksum "package-lock.json" }}
            - starter-kit-deps- # fallback
      - run:
          name: Install dependencies
          command: npm ci
      - run:
          name: End-to-end test
          command: npm run e2e
      - store_test_results:
          path: ./reports
      - store_artifacts:
          path: ./e2e/screenshots
          destination: screenshots
  verify-boron:
    environment:
      NODE_RELEASE: boron
    <<: *defaults
    <<: *docker-e2e
  verify-carbon:
    environment:
      NODE_RELEASE: carbon
    <<: *defaults
    <<: *docker-e2e
  verify-dubnium:
    environment:
      NODE_RELEASE: dubnium
    <<: *defaults
    <<: *docker-e2e

workflows:
  build:
    jobs:
      - deps
      - test:
          requires:
            - deps
      - e2e:
          requires:
            - deps
            - test

  verify:
    jobs:
      - verify-boron
      - verify-carbon
      - verify-dubnium
